Arguments checks

diff --git a/rattles b/rattles
--- a/rattles
+++ b/rattles
@@ -4,10 +4,18 @@
 
 function bell {
   [[ -z "${1}" ]] && echo "Provide duration" && return 1
+
+  ! [[ "${1}" =~ ^(0x[[:xdigit:].]+|[0-9.]+)[smhd]?$ ]] && \
+    echo "Invalid duration" && return 1
+
+  tput bel
+  sleep "${1}" > /dev/null 2>&1
+  [[ "${?}" -ne 0 ]] && echo "Invalid durtation" && return 1
+
   while true
   do
     tput bel
-    sleep "${1}"
+    sleep "${1}" > /dev/null 2>&1
   done
 }
 
@@ -38,7 +46,7 @@ function rattles {
   count="${1}"
 
   (
-    ! [[ "${count}" =~ ^(0x)?[0-9[:xdigit:]]+$ ]] || \
+    ! [[ "${count}" =~ ^[0-9]+$ ]] || \
     [[ "${count}" -lt 1 ]] || \
     [[ "${count}" -gt 8 ]]
   ) && echo "Too many rattles" && return 1
@@ -51,8 +59,7 @@ function rattles {
     idx="$(index "${t}" tims)"
     unset "tims["${idx}"]"
   done
-  #echo "${bell_tims[@]}"
-  echo "${bell_tims[@]}" | xargs -n 1 -P "${1}" "${g_mypath}" "bell" 
+  echo "${bell_tims[@]}" | xargs -n 1 -P "${1}" "${g_mypath}" "bell"
 }
 
 [[ -z "${1}" ]] && exit 1
@@ -90,16 +97,6 @@ function rattles {
     echo -e "\t\trepeats ringing if "bell" is used. Otherwise this shall "
     echo -e "\t\tbe the duration till which the rattle is played."
     echo
-
-#EXAMPLES
-#    your_command_name "foo" 42
-#    your_command_name 30
-#    your_command_name 0x1E
-#
-#EXIT STATUS
-#    0   Success
-#    1   Invalid arguments
-#    2   Missing second argument when "foo" is specified
   } && exit 0
 
 [[ "${1}" == "bell" ]] && (bell "${2}" || true) && exit 0
@@ -107,5 +104,8 @@ function rattles {
 set_mypath
 
 [[ -z "${2}" ]] && (rattles "${1}" || true) && exit 0
+
+! [[ "${2}" =~ ^(0x[[:xdigit:].]+|[[0-9.]+)[smhd]?$ ]] && \
+  echo "Invalid duration" && exit 1
 
 timeout "${2}" "${g_mypath}" "${1}"
